"""empty message

Revision ID: 8ac8e50812d8
Revises: e0b34625ebce
Create Date: 2024-12-10 21:18:57.092425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac8e50812d8'
down_revision = 'e0b34625ebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.TEXT(length=100), nullable=False))

    # ### end Alembic commands ###
